In [1]:
import pandas as pd
import numpy as np

In [4]:
#Listing.csv

listing_df = pd.read_csv("listings.csv")
listing_df.head(5)

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,2708,"Run Runyon, Beaut Furn Mirror Mini-Suit w/ Fir...",3008,1.462506e+18,Chas.,City of Los Angeles,Hollywood,34.09625,-118.34605,Private room,NaN,30,46,2025-09-04,0.33,2,324,2,NaN
1,2732,Zen Life at the Beach,3041,1.462506e+18,Louise-Diane,Other Cities,Santa Monica,34.00440,-118.48095,Private room,NaN,7,24,2022-08-21,0.14,2,350,0,228269
2,2864,* Beautiful Master Suite/Jacuzzi Tub/*,3207,1.462506e+18,Bernadine,Other Cities,Bellflower,33.87490,-118.11515,Entire home/apt,NaN,30,0,NaN,NaN,1,0,0,NaN
3,6033,Poolside Serenity Studio,11619,1.462507e+18,Sarah,City of Los Angeles,Woodland Hills,34.16887,-118.64478,Entire home/apt,NaN,30,19,2020-03-22,0.10,6,270,0,NaN
4,6931,"RUN Runyon, Beau Furn Rms Terrace Hollyw Hill ...",3008,1.462506e+18,Chas.,City of Los Angeles,Hollywood,34.09626,-118.34372,Private room,NaN,30,38,2025-09-10,0.19,2,355,4,NaN

In [6]:
#Reviews.csv

review_df = pd.read_csv("reviews.csv")
review_df.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,2708,13994902,2014-06-09,10905424,Kuberan,i had a wonderful stay. Everything from start ...
1,2708,14606598,2014-06-23,2247288,Camilla,Charles is just amazing and he made my stay sp...
2,2708,39597339,2015-07-25,27974696,Fallon,Staying with Chas was an absolute pleasure. He...
3,2708,61157407,2016-02-01,33226412,Haroon,Charles is a most wonderful host. I enjoyed my...
4,2708,66196280,2016-03-20,23408691,Massimo Litterio,Chas is a really good host. He gives me a lot ...

In [7]:
#Neighbouthoods.csv

neighbors_df = pd.read_csv("neighbourhoods.csv")
neighbors_df.head()

   neighbourhood_group           neighbourhood
0  City of Los Angeles         Adams-Normandie
1  City of Los Angeles                  Arleta
2  City of Los Angeles       Arlington Heights
3  City of Los Angeles         Atwater Village
4  City of Los Angeles  Baldwin Hills/Crenshaw

In [9]:
#Neighbourhood.geojson

import json

with open("neighbourhoods.geojson", "r", encoding="utf-8") as f:
    data = json.load(f)

print(data.keys())          # see structure
print(len(data["features"]))

# First feature
print(data["features"][0])

# First 5 features
print(data["features"][:5])

dict_keys(['type', 'features'])
270